# OpenSearch ML Quickstart Configuration (Dynaconf)
# This file uses a flat YAML structure (variable: value format)

# Project paths and environment
QANDA_FILE_READER_PATH: ./datasets

# OpenSearch configuration
MINIMUM_OPENSEARCH_VERSION: 2.19.0

# ML connectors, models and model_groups
ML_BASE_URI: /_plugins/_ml
DELETE_RESOURCE_WAIT_TIME: 5
DELETE_RESOURCE_RETRY_TIME: 5

# Default model configuration
DEFAULT_LOCAL_MODEL_NAME: huggingface/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
DEFAULT_MODEL_VERSION: 1.0.1
DEFAULT_MODEL_FORMAT: TORCH_SCRIPT

# Pipeline configuration
PIPELINE_FIELD_MAP:
  chunk: chunk_embedding

# OpenSource (OS) OpenSearch
OS_USERNAME: 
OS_PASSWORD: 
OS_HOST_URL: 
OS_PORT: 

# Amazon OpenSearch Service (AOS)
AOS_USERNAME: 
AOS_PASSWORD: 
AOS_DOMAIN_NAME: 
AOS_HOST_URL: 
AOS_PORT: 
AOS_REGION: 
AOS_AWS_USER_NAME: 

# OS + Sagemaker configurations
OS_SAGEMAKER_ACCESS_KEY: 
OS_SAGEMAKER_SECRET_KEY: 
OS_SAGEMAKER_REGION: 
OS_SAGEMAKER_CONNECTOR_VERSION: 
OS_SAGEMAKER_SPARSE_URL: 
OS_SAGEMAKER_DENSE_URL: 
OS_SAGEMAKER_DENSE_MODEL_DIMENSION: 

# AOS + Sagemaker configurations
AOS_SAGEMAKER_SPARSE_ARN: 
AOS_SAGEMAKER_DENSE_ARN: 
AOS_SAGEMAKER_CONNECTOR_ROLE_NAME: 
AOS_SAGEMAKER_CREATE_CONNECTOR_ROLE_NAME: 
AOS_SAGEMAKER_REGION: 
AOS_SAGEMAKER_CONNECTOR_VERSION: 1.0
AOS_SAGEMAKER_SPARSE_URL: 
AOS_SAGEMAKER_DENSE_URL: 
AOS_SAGEMAKER_DENSE_MODEL_DIMENSION: 

# OS + Bedrock configurations
OS_BEDROCK_ACCESS_KEY: 
OS_BEDROCK_SECRET_KEY: 
OS_BEDROCK_REGION: 
OS_BEDROCK_CONNECTOR_VERSION: 1.0
OS_BEDROCK_URL: 
OS_BEDROCK_MODEL_DIMENSION: 

# AOS + Bedrock configurations
AOS_BEDROCK_ARN: 
AOS_BEDROCK_CONNECTOR_ROLE_NAME: 
AOS_BEDROCK_CREATE_CONNECTOR_ROLE_NAME: 
AOS_BEDROCK_REGION: 
AOS_BEDROCK_CONNECTOR_VERSION: 1.0
AOS_BEDROCK_URL: 
AOS_BEDROCK_MODEL_DIMENSION: 
